services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker.gpu
    image: asr-worker-gpu
    container_name: asr-worker-gpu
    environment:
      - COMPUTE_DEVICE=cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]