version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: asr-api
    ports:
      - "8000:8000"
    volumes:
      - audio_data:/shared/audio
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker.cpu
    container_name: asr-worker-cpu
    volumes:
      - audio_data:/shared/audio
    environment:
      - COMPUTE_DEVICE=cpu
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          memory: 10g
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis
    container_name: asr-redis
    restart: unless-stopped

volumes:
  audio_data: